[project]
name = "protein-av"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools]
py-modules = ["modules"]

[tool.setuptools.packages.find]
where = ["src"]

